accent = "#76ff03"
cursor = "#e4d8b4"
foreground = "#e4d8b4"
background = "#1d271f"
selection_foreground = "#f2eadc"
selection_background = "#505b51"

color0 = "#293427"
color1 = "#c45b5b"
color2 = "#7e9c58"
color3 = "#d29c5a"
color4 = "#65a0d9"
color5 = "#d6885e"
color6 = "#89d9d0"
color7 = "#e4d8b4"
color8 = "#505b51"
color9 = "#e67373"
color10 = "#99bf6b"
color11 = "#efb064"
color12 = "#82bbff"
color13 = "#f09968"
color14 = "#a5f5ef"
color15 = "#f5ebd1"
