background = #1d271f
foreground = #e4d8b4
cursor-color = #e4d8b4
selection-background = #505b51
selection-foreground = #f2eadc

palette = 0=#293427
palette = 1=#c45b5b
palette = 2=#7e9c58
palette = 3=#d29c5a
palette = 4=#65a0d9
palette = 5=#d6885e
palette = 6=#89d9d0
palette = 7=#e4d8b4
palette = 8=#505b51
palette = 9=#e67373
palette = 10=#99bf6b
palette = 11=#efb064
palette = 12=#82bbff
palette = 13=#f09968
palette = 14=#a5f5ef
palette = 15=#f5ebd1
