# SUPER + CTRL: system toggles, menus, panels, notifications, power.

$scripts = $HOME/nixos-dotfiles/config/scripts

# Menus
bind = SUPER, code:19, exec, $scripts/nix-menu-theming # SUPER + 0: theme, background, power
bind = SUPER CTRL, SPACE, exec, $scripts/nix-menu-keybindings

# Toggles
bind = SUPER CTRL, I, exec, nix-toggle-idle
bind = SUPER CTRL, L, exec, nix-lock-screen
bind = SUPER CTRL, COMMA, exec, nix-toggle-notification-silencing
bind = SUPER SHIFT, SPACE, exec, nix-toggle-waybar
bind = SUPER CTRL SHIFT, BACKSPACE, exec, nix-hyprland-window-gaps-toggle

# Captures
bind = SUPER SHIFT, S, exec, nix-cmd-screenshot

# Control panels
bind = SUPER CTRL, A, exec, alacritty -e pulsemixer
bind = SUPER CTRL, W, exec, alacritty -e nmtui
bind = SUPER CTRL, T, exec, alacritty --class TUI.float -e btop

# Notifications
bind = SUPER, COMMA, exec, makoctl dismiss
bind = SUPER SHIFT, COMMA, exec, makoctl dismiss --all

# Power
bind = SUPER, ESCAPE, exec, systemctl poweroff
