#!/usr/bin/env bash

# A menu for theming, shortcuts, and system power actions

CHOICE=$(echo -e "󱄄  Change Theme
󰸉  Change Background
⌨️  View Shortcuts
󰌾  Lock
󰍃  Logout
󰜉  Reboot
⏻  Shutdown" | fuzzel --dmenu -p "" --placeholder "System & Theming…")

case "$CHOICE" in
    *Theme*)
        "$HOME/nixos-dotfiles/config/scripts/nix-theme-selector"
        ;;
    *Background*)
        "$HOME/nixos-dotfiles/config/scripts/nix-background-selector"
        ;;
    *Shortcuts*)
        "$HOME/nixos-dotfiles/config/scripts/nix-menu-keybindings"
        ;;
    *Lock*)
        "$HOME/nixos-dotfiles/config/scripts/nix-lock-screen"
        ;;
    *Logout*)
        hyprctl dispatch exit
        ;;
    *Reboot*)
        systemctl reboot
        ;;
    *Shutdown*)
        systemctl poweroff
        ;;
esac
