#!/usr/bin/env bash

# Launch or focus on a given TUI identified by the passed in as the command.
# Use by commands like nix-launch-wifi to ensure there is only one wifi configuration screen open.

APP_ID="org.arch.$(basename "$1")"
LAUNCH_COMMAND="nix-launch-tui $@"

exec nix-launch-or-focus "$APP_ID" "$LAUNCH_COMMAND"
