foreground #fff8ed
background #0F0F06
selection_foreground #fff8ed
selection_background #989862

cursor #fff8ed
cursor_text_color #0F0F06

active_border_color #a6c671
active_tab_background #a6c671

color0 #0F0F06
color1 #f66732
color2 #a6c671
color3 #fae34c
color4 #f85a04
color5 #e29983
color6 #a9c2cb
color7 #FAD296
color8 #989862
color9 #ffa685
color10 #d0e3b0
color11 #fff3a3
color12 #d1dbe0
color13 #f5d5cc
color14 #e2ebee
color15 #fff8ed
