# Application bindings
bind = SUPER, RETURN, exec, uwsm-app -- xdg-terminal-exec --dir="$(nix-cmd-terminal-cwd)"
bind = SUPER ALT, RETURN, exec, uwsm-app -- xdg-terminal-exec --dir="$(nix-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bind = SUPER SHIFT, RETURN, exec, nix-launch-browser
bind = SUPER SHIFT, F, exec, uwsm-app -- nautilus --new-window
bind = SUPER ALT SHIFT, F, exec, uwsm-app -- nautilus --new-window "$(nix-cmd-terminal-cwd)"
bind = SUPER SHIFT, B, exec, nix-launch-browser
bind = SUPER SHIFT ALT, B, exec, nix-launch-browser --private
bind = SUPER SHIFT, M, exec, nix-launch-or-focus spotify
bind = SUPER SHIFT, N, exec, nix-launch-editor
bind = SUPER SHIFT, D, exec, nix-launch-tui lazydocker
bind = SUPER SHIFT, G, exec, nix-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bind = SUPER SHIFT, O, exec, nix-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bind = SUPER SHIFT, W, exec, uwsm-app -- typora --enable-wayland-ime
bind = SUPER SHIFT, SLASH, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bind = SUPER SHIFT, A, exec, launch-webapp "https://chatgpt.com"
bind = SUPER SHIFT ALT, A, exec, launch-webapp "https://grok.com"
bind = SUPER SHIFT, C, exec, launch-webapp "https://app.hey.com/calendar/weeks/"
bind = SUPER SHIFT, E, exec, launch-webapp "https://app.hey.com"
bind = SUPER SHIFT, Y, exec, launch-webapp "https://youtube.com/"
bind = SUPER SHIFT ALT, G, exec, nix-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bind = SUPER SHIFT CTRL, G, exec, nix-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bind = SUPER SHIFT, P, exec, nix-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bind = SUPER SHIFT, X, exec, launch-webapp "https://x.com/"
bind = SUPER SHIFT ALT, X, exec, launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bind = SUPER, SPACE, exec, nix-menu
