# Application bindings
bind = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(nix-cmd-terminal-cwd)"
bind = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(nix-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bind = SUPER SHIFT, RETURN, Browser, exec, nix-launch-browser
bind = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bind = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(nix-cmd-terminal-cwd)"
bind = SUPER SHIFT, B, Browser, exec, nix-launch-browser
bind = SUPER SHIFT ALT, B, Browser (private), exec, nix-launch-browser --private
bind = SUPER SHIFT, M, Music, exec, nix-launch-or-focus spotify
bind = SUPER SHIFT, N, Editor, exec, nix-launch-editor
bind = SUPER SHIFT, D, Docker, exec, nix-launch-tui lazydocker
bind = SUPER SHIFT, G, Signal, exec, nix-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bind = SUPER SHIFT, O, Obsidian, exec, nix-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bind = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bind = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bind = SUPER SHIFT, A, ChatGPT, exec, launch-webapp "https://chatgpt.com"
bind = SUPER SHIFT ALT, A, Grok, exec, launch-webapp "https://grok.com"
bind = SUPER SHIFT, C, Calendar, exec, launch-webapp "https://app.hey.com/calendar/weeks/"
bind = SUPER SHIFT, E, Email, exec, launch-webapp "https://app.hey.com"
bind = SUPER SHIFT, Y, YouTube, exec, launch-webapp "https://youtube.com/"
bind = SUPER SHIFT ALT, G, WhatsApp, exec, nix-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bind = SUPER SHIFT CTRL, G, Google Messages, exec, nix-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bind = SUPER SHIFT, P, Google Photos, exec, nix-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bind = SUPER SHIFT, X, X, exec, launch-webapp "https://x.com/"
bind = SUPER SHIFT ALT, X, X Post, exec, launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bind = SUPER, SPACE, Omarchy menu, exec, nix-menu
