# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (relative paths)
source = ../default/hypr/autostart.conf
source = ../default/hypr/bindings/media.conf
source = ../default/hypr/bindings/clipboard.conf
source = ../default/hypr/bindings/tiling-v2.conf
source = ../default/hypr/bindings/utilities.conf
source = ../default/hypr/envs.conf
source = ../default/hypr/looknfeel.conf
source = ../default/hypr/input.conf
source = ../default/hypr/windows.conf
source = ./theme.conf

# Change your own setup in these files
source = ./monitors.conf
source = ./input.conf
source = ./bindings.conf
source = ./looknfeel.conf
source = ./autostart.conf
