# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults
source = ~/.config/default/hypr/autostart.conf
source = ~/.config/default/hypr/bindings/media.conf
source = ~/.config/default/hypr/bindings/clipboard.conf
source = ~/.config/default/hypr/bindings/tiling-v2.conf
source = ~/.config/default/hypr/bindings/utilities.conf
source = ~/.config/default/hypr/envs.conf
source = ~/.config/default/hypr/looknfeel.conf
source = ~/.config/default/hypr/input.conf
source = ~/.config/default/hypr/windows.conf
source = ~/.config/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
