# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#15141b"

# Main text color
theme[main_fg]="#edecee"

# Title color for boxes
theme[title]="#edecee"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#a277ff"

# Background color of selected item in processes box
theme[selected_bg]="#4d4d4d"

# Foreground color of selected item in processes box
theme[selected_fg]="#a277ff"

# Color of inactive/disabled text
theme[inactive_fg]="#4d4d4d"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#edecee"

# Background color of the percentage meters
theme[meter_bg]="#4d4d4d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#edecee"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#a277ff"
theme[mem_box]="#61ffca"
theme[net_box]="#ff6767"
theme[proc_box]="#a277ff"

# Box divider line and small boxes line color
theme[div_line]="#4d4d4d"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#61ffca"
theme[temp_mid]="#ffca85"
theme[temp_end]="#ff6767"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#61ffca"
theme[cpu_mid]="#a277ff"
theme[cpu_end]="#a277ff"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#a277ff"
theme[free_mid]="#a277ff"
theme[free_end]="#61ffca"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#a277ff"
theme[cached_mid]="#61ffca"
theme[cached_end]="#a277ff"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#ffca85"
theme[available_mid]="#ff6767"
theme[available_end]="#ff6767"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#61ffca"
theme[used_mid]="#61ffca"
theme[used_end]="#a277ff"

# Download graph colors (Peach -> Red)
theme[download_start]="#ffca85"
theme[download_mid]="#ff6767"
theme[download_end]="#ff6767"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#61ffca"
theme[upload_mid]="#61ffca"
theme[upload_end]="#a277ff"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#61ffca"
theme[process_mid]="#a277ff"
theme[process_end]="#a277ff"
