return {
  -- Force EVERY plugin to load on startup
  { "LazyVim", lazy = false },
  { "blink.cmp", lazy = false },
  { "bufferline.nvim", lazy = false },
  { "catppuccin", lazy = false },
  { "conform.nvim", lazy = false },
  { "flash.nvim", lazy = false },
  { "friendly-snippets", lazy = false },
  { "gitsigns.nvim", lazy = false },
  { "grug-far.nvim", lazy = false },
  { "lazydev.nvim", lazy = false },
  { "lualine.nvim", lazy = false },
  { "mini.ai", lazy = false },
  { "mini.icons", lazy = false },
  { "mini.pairs", lazy = false },
  { "noice.nvim", lazy = false },
  { "nui.nvim", lazy = false },
  { "nvim-lint", lazy = false },
  { "nvim-lspconfig", lazy = false },
  { "nvim-treesitter", lazy = false },
  { "nvim-treesitter-textobjects", lazy = false },
  { "nvim-ts-autotag", lazy = false },
  { "persistence.nvim", lazy = false },
  { "plenary.nvim", lazy = false },
  { "snacks.nvim", lazy = false, priority = 1000 },
  { "todo-comments.nvim", lazy = false },
  { "tokyonight.nvim", lazy = false, priority = 1000 },
  { "trouble.nvim", lazy = false },
  { "ts-comments.nvim", lazy = false },
  { "which-key.nvim", lazy = false },
  { "obsidian.nvim", lazy = false },
  -- Migrated Plugins
  { "auto-session", lazy = false },
  { "substitute.nvim", lazy = false },
  { "vim-maximizer", lazy = false },
  { "vim-tmux-navigator", lazy = false },
}
